name: Deploy Vite to GitHub Pages

on:
  push:
    branches:
      - main # 기본 브랜치가 main일 경우
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Node.js 환경 설정
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 # Node.js 최신 버전

      # 3. 종속성 설치 및 빌드
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      # 4. 빌드 결과 업로드
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      # 5. GitHub Pages 배포
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
