name: Deploy Vite to GitHub Pages

on:
  # Push 이벤트가 발생할 때 워크플로우 실행
  push:
    branches:
      - master # master 브랜치에 Push될 때 실행. 필요하면 main으로 변경

  # Actions 탭에서 수동 실행 허용
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Node.js 환경 설정
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Node.js 버전 설정 (Vite 요구사항: 16 이상)

      # 3. 종속성 설치 및 빌드
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build # Vite 빌드 실행

      # 4. GitHub Pages 배포를 위한 빌드 결과 업로드
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist # Vite 빌드 결과 디렉토리 (기본값: dist)

      # 5. GitHub Pages에 배포
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
